-- ─────────────────────────────────────────────────────────────────────────────
-- HOPSI H-OS · Supabase Storage Infrastructure
-- Run these statements in the Supabase SQL Editor in order.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── 1. Create Buckets ────────────────────────────────────────────────────────

-- avatars: Public bucket for employee profile photos.
-- Only image files are allowed. Max size enforced by API layer (2MB).
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'avatars',
  'avatars',
  true,
  2097152,  -- 2MB in bytes
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

-- legal-docs: Private bucket for employee and tenant legal documents.
-- Max size enforced by API layer (5MB). Signed URLs required for access.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'legal-docs',
  'legal-docs',
  false,
  5242880,  -- 5MB in bytes
  ARRAY['application/pdf', 'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'image/jpeg', 'image/png']
)
ON CONFLICT (id) DO NOTHING;

-- reports: Private bucket for generated financial and operational reports.
-- Max size enforced by API layer (5MB). Signed URLs required for access.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'reports',
  'reports',
  false,
  5242880,  -- 5MB in bytes
  ARRAY['application/pdf',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'text/csv']
)
ON CONFLICT (id) DO NOTHING;

-- ─── 2. RLS Policies: avatars (Public Bucket) ──────────────────────────────────
-- Anyone can view public avatars (they are for display).
-- Upload requires authenticated user, path must match {tenant_id}/{eid}/ pattern.

CREATE POLICY "Avatar public read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'avatars');

CREATE POLICY "Avatar authenticated upload"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'avatars'
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "Avatar owner delete"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'avatars'
    AND auth.role() = 'authenticated'
  );

-- ─── 3. RLS Policies: legal-docs (Private Bucket) ─────────────────────────────
-- Authenticated users can upload under their tenant's folder.
-- Read is restricted — must use Signed URL generated by the API service.
-- Principle: DB stores the path only; the signed URL is generated per-request with expiry.

CREATE POLICY "Legal docs authenticated upload"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'legal-docs'
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "Legal docs authenticated read"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'legal-docs'
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "Legal docs authenticated delete"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'legal-docs'
    AND auth.role() = 'authenticated'
  );

-- ─── 4. RLS Policies: reports (Private Bucket) ────────────────────────────────

CREATE POLICY "Reports authenticated upload"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'reports'
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "Reports authenticated read"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'reports'
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "Reports authenticated delete"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'reports'
    AND auth.role() = 'authenticated'
  );

-- ─────────────────────────────────────────────────────────────────────────────
-- STRATEGY NOTE:
-- Files are NEVER stored as binary in the database.
-- The database stores ONLY the storage path (string), e.g.:
--   dim_employee.foto_url = 'avatars/{tenant_id}/{eid}/avatar.jpg'
--   dim_employee.contract_path = 'legal-docs/{tenant_id}/{eid}/contract.pdf'
--
-- Retrieval pattern for private files:
--   1. Read the path from dim_employee / dim_tenant.
--   2. Call StorageService.getSignedUrl(bucket, path) → returns a temporary URL (1 hour).
--   3. Present the signed URL to the client for download/display.
-- ─────────────────────────────────────────────────────────────────────────────
